name: Cashit
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup System
        run: |
          sudo apt-get install libsqlite3-dev
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint
        run: |
          poetry run pre-commit install-hooks
          poetry run pre-commit run --all-files
      - name: Test
        run: poetry run pytest
      - name: report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cov.xml
          name: codecov-umbrella
          fail_ci_if_error: true
